/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticket.ui;

import exam.manager.TicketManager;
import exam.ticket.entites.Ticket;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class TicketList extends javax.swing.JInternalFrame {

    TicketManager ticketManager = new TicketManager();

    public void loadTicketList() {
        List<Ticket> data = ticketManager.getAllTicket();

        DefaultTableModel defaultTableModel = (DefaultTableModel) tblListTicket.getModel();
        if (data.size() > 0) {
            defaultTableModel.setRowCount(0);
            for (Ticket ticket : data) {
                defaultTableModel.addRow(new Object[]{ticket.getId(), ticket.getPassenger(),
                    ticket.getPhone(), ticket.getFromSName(), ticket.getToSName(),
                    ticket.getType(), ticket.getStartDate(), ticket.getEndDate()});
            }
        }
        tblListTicket.setModel(defaultTableModel);
    }

    /**
     * Creates new form TicketList
     */
    public TicketList() {
        initComponents();
        loadTicketList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        MenuEdit = new javax.swing.JMenuItem();
        MenuRemove = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListTicket = new javax.swing.JTable();

        MenuEdit.setText("Sửa");
        MenuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditActionPerformed(evt);
            }
        });
        popupMenu.add(MenuEdit);

        MenuRemove.setText("Xóa");
        MenuRemove.setToolTipText("");
        MenuRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRemoveActionPerformed(evt);
            }
        });
        popupMenu.add(MenuRemove);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Danh sách đặt vé");

        tblListTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã vé", "Tên hành khách", "Số điện thoại", "Ga đi", "Ga đến", "Loại vé", "Ngày đi", "Ngày đến"
            }
        ));
        tblListTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblListTicketMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblListTicket);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblListTicketMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListTicketMouseReleased
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON3) {
            if (evt.isPopupTrigger() && tblListTicket.getSelectedRowCount() != 0) {
                this.add(popupMenu);
                popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tblListTicketMouseReleased

    private void MenuRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRemoveActionPerformed
        // TODO add your handling code here:
        int indexTicket = (int) tblListTicket.getValueAt(tblListTicket.getSelectedRow(), 0);
        ticketManager.removeTicketById(indexTicket);
        loadTicketList();
    }//GEN-LAST:event_MenuRemoveActionPerformed

    private void MenuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditActionPerformed
        // TODO add your handling code here:
            int indexTicket = (int) tblListTicket.getValueAt(tblListTicket.getSelectedRow(), 0);
            TicketInfo ticketInfo = new TicketInfo(indexTicket);
            this.getParent().add(ticketInfo);
            ticketInfo.setVisible(true);
    }//GEN-LAST:event_MenuEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuEdit;
    private javax.swing.JMenuItem MenuRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JTable tblListTicket;
    // End of variables declaration//GEN-END:variables
}
